package com.example.rot.uitotem;/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 5;
  /** RegularExpression Id. */
  int CLASS = 6;
  /** RegularExpression Id. */
  int INT = 7;
  /** RegularExpression Id. */
  int CHAR = 8;
  /** RegularExpression Id. */
  int SEMICOLON = 9;
  /** RegularExpression Id. */
  int LEFT_BRACKET = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 12;
  /** RegularExpression Id. */
  int SELECTDEPUTY = 13;
  /** RegularExpression Id. */
  int AS = 14;
  /** RegularExpression Id. */
  int FROM = 15;
  /** RegularExpression Id. */
  int WHERE = 16;
  /** RegularExpression Id. */
  int DROP = 17;
  /** RegularExpression Id. */
  int INSERT = 18;
  /** RegularExpression Id. */
  int INTO = 19;
  /** RegularExpression Id. */
  int VALUES = 20;
  /** RegularExpression Id. */
  int DELETE = 21;
  /** RegularExpression Id. */
  int SELECT = 22;
  /** RegularExpression Id. */
  int UPDATE = 23;
  /** RegularExpression Id. */
  int SET = 24;
  /** RegularExpression Id. */
  int OR = 25;
  /** RegularExpression Id. */
  int AND = 26;
  /** RegularExpression Id. */
  int NOT = 27;
  /** RegularExpression Id. */
  int DOT = 28;
  /** RegularExpression Id. */
  int CROSS = 29;
  /** RegularExpression Id. */
  int SINGLE = 30;
  /** RegularExpression Id. */
  int BIGGEREQUAL = 31;
  /** RegularExpression Id. */
  int LESSEQUAL = 32;
  /** RegularExpression Id. */
  int NOTEQUAL = 33;
  /** RegularExpression Id. */
  int EQUAL = 34;
  /** RegularExpression Id. */
  int BIGGER = 35;
  /** RegularExpression Id. */
  int LESS = 36;
  /** RegularExpression Id. */
  int PLUS = 37;
  /** RegularExpression Id. */
  int MINUS = 38;
  /** RegularExpression Id. */
  int MULT = 39;
  /** RegularExpression Id. */
  int DIV = 40;
  /** RegularExpression Id. */
  int STRING = 41;
  /** RegularExpression Id. */
  int INTNUMBER = 42;
  /** RegularExpression Id. */
  int ID = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<CREATE>",
    "<CLASS>",
    "<INT>",
    "<CHAR>",
    "\";\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "<SELECTDEPUTY>",
    "<AS>",
    "<FROM>",
    "<WHERE>",
    "<DROP>",
    "<INSERT>",
    "<INTO>",
    "<VALUES>",
    "<DELETE>",
    "<SELECT>",
    "<UPDATE>",
    "<SET>",
    "<OR>",
    "<AND>",
    "<NOT>",
    "\".\"",
    "\"->\"",
    "\"\\\'\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<STRING>",
    "<INTNUMBER>",
    "<ID>",
  };

}
